services:
  app:
    image: app:latest
    container_name: app
    build: ./Dockerfile
    ports:
      - "8082:8082"
    restart: always
    env_file:
      - cmd/auth/config.env
    networks:
      - app

networks:
  app:
    driver: bridge
    
