openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
  description: API для авторизации и обновления токенов
servers:
  - url: http://localhost:8080
    description: Локальный сервер

paths:
  /login:
    get:
      summary: Вход и получение токенов
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: integer
          description: Идентификатор пользователя
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Answer'
        '400':
          description: Ошибка запроса
        '401':
          description: Необходимо авторизоваться
        '500':
          description: Внутренняя ошибка сервера

  /refresh:
    get:
      summary: Обновление токенов
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: integer
          description: Идентификатор пользователя
      responses:
        '200':
          description: Токены успешно обновлены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Answer'
        '400':
          description: Ошибка запроса
        '401':
          description: Необходимо авторизоваться
        '500':
          description: Внутренняя ошибка сервера

components:
  schemas:
    Answer:
      type: object
      properties:
        access:
          type: string
          description: Токен доступа
        refresh:
          type: string
          description: Токен обновления
